top.modern_horror = [
    {
        title: "Gothic Themes & Motifs",
        id: "gothic_motifs",
        roll: [
            "Addiction",
            "Assassination",
            "Banditry",
            "Betrayal",
            "Blood",
            "Burial Alive",
            "Cannibalism",
            "Carnival",
            "Cold",
            "Corruption",
            "Damnation",
            "Darkness",
            "The Dead",
            "Decay",
            "Deformity",
            "The Demimonde",
            "Disease",
            "Disembodied Voices",
            "Deception (lies, disguises, etc.)",
            "Disinterment",
            "Dwarfism",
            "Envy",
            "Everything Goes Wrong",
            "Exile",
            "Fallen Nobility",
            "Fire",
            "Fog",
            "Folly",
            "Forbidden Knowledge",
            "Foreigners",
            "Frightening Animals (ravens, crows, wolves, owls, toads)",
            "Gambling",
            "Ghosts",
            "Giants",
            "Gluttony",
            "Grave Robbing",
            "Greed",
            "Gypsies",
            "Hidden Ancestry",
            "Honor",
            "Hypnotism",
            "Immortality",
            "Imperiled Virtue",
            "Imprisonment",
            "Incest",
            "Indolence",
            "Infidelity",
            "Inheritance",
            "Injustice",
            "Irredeemable Sin",
            "Irresistible Fate",
            "Jealousy",
            "The Last Remaining…",
            "Lightning",
            "Look-Alikes",
            "Love Gone Sour (love lost, love that becomes abusive, etc.)",
            "Loveless Marriage",
            "Lust",
            "Masks",
            "Melancholy",
            "Mistaken Identity",
            "Murder",
            "Music",
            "Mysterious Manuscripts",
            "Nightmares",
            "Oaths and Promises",
            "Perversion",
            "Poison",
            "Pride",
            "Primitive Savages",
            "Prophesy",
            "Prostitution",
            "Rape",
            "Revenge",
            "Rituals and Superstitions",
            "Sacrifice and Loss",
            "Savage Nature",
            "Secret Passages",
            "Secret Societies",
            "Seduction",
            "Slavery",
            "Sleep-walking",
            "Sorcery",
            "Storms",
            "Suicide",
            "Theft",
            "Tombs",
            "Torture",
            "Transformation",
            "True Love",
            "Twisted Religion",
            "Unforeseen Consequences",
            "Usurpation",
            "Vampires",
            "Ventriloquism",
            "Wandering",
            "War",
            "Weird Medicine",
            "Werewolves",
            "Wine"
        ]

    },
    {
        title: "Typical Events in a Gothic Story",
        id: "gothic_events",
        roll: [
            "An Abduction",
            "The Black Sabbath",
            "A Blizzard",
            "A Circus",
            "A Costumed Religious Procession",
            "A Deal With the Devil",
            "A Disembodied Voice is Heard",
            "A Dissection",
            "A Door Opens By Itself",
            "A Drowning",
            "An Earthquake",
            "An Empty Suit of Armor Moves",
            "An Erotic Dance",
            "An Execution",
            "An Exhumation",
            "A Forced Internment in a Convent or Monastery",
            "A Forced Wedding",
            "A Fortune Reading",
            "A Game of Cards or Dice",
            "A Ghost Appears",
            "An Improbable Transformation",
            "A Lightning Strike",
            "A Masquerade Ball",
            "A Murder",
            "An Opium-Induced Dream",
            "A Portrait Being Painted",
            "A Prisoner is Rescued",
            "A Protracted Illness",
            "A Puppet Show (Marionettes, Dummies, or Shadow Puppets)",
            "A Purse-Snatching",
            "A Room Becomes Inexplicably Cold",
            "A Salon is Held",
            "A Secret Room or Passage is Discovered",
            "A Sham Trial",
            "A Skeleton Moves",
            "A Statue Walks",
            "A Story is Told by a Fire",
            "A Stranger Knocks on the Door",
            "A Strange Letter is Delivered",
            "A Thunder Storm",
            "A Vampire Attack",
            "A Violation",
            "A Wolf Attack",
        ]
    },
    {
        id: "gothic_locations",
        title: "Gothic Locations",
        roll: [
            "A Blasted Tree",
            "A Cave",
            "A Crossroads",
            "A Dark Forest",
            "A Dark Lake",
            "The Gallows or Hanging Tree",
            "A Gypsy Camp",
            "A Hill On An Otherwise Level Plain",
            "A Miasmal Swamp",
            "The Moors",
            "A Narrow, Crooked Street",
            "An Old Battlefield.",
            "An Overgrown Garden",
            "A Plantation",
            "A Refuse Dump",
            "A Road Through The Wilderness",
            "The Site Of A Legendary Crime",
            "A Slave Market",
            "A Stark Mountain Side",
            "A Well",
            "An Isolated Village"
        ]
    },
    {
        id: "gothic_buildings",
        title: "Gothic Buildings",
        roll: [
            "An Ancient Abbey",
            "An Asylum",
            "A Black Passenger Carriage",
            "A Brothel",
            "A Dark Castle",
            "A Drawing Room",
            "A Gambling House",
            "A House Built On the Site Of An Ancient Temple",
            "An Inn Filled With Unfriendly People",
            "A Manor House",
            "An Old Convent",
            "An Old Mill",
            "An Opium Den",
            "A Prison",
            "A Ruined Temple",
            "A Seemingly Deserted Ship",
            "The Sewers",
            "A Slaughterhouse",
            "The Stables",
            "A Theater",
            "A Wax Museum",
            "A Wrecked Ship"
        ]
    }, {
        id: "gothic_parts_buildings",
        title: "Gothic Parts of Buildings",
        roll: [
            "The Ball Room",
            "The Catacombs",
            "The Cells",
            "The Concealed Chamber of Magic",
            "The Forbidden Wing Of An Ancestral Home",
            "The Forgotten Nursery",
            "Gargoyles",
            "The Harem",
            "The Initiation Chamber",
            "The Laboratory",
            "A Locked Tower",
            "The Obscenely-Decorated Bedchamber",
            "The Operating Theater",
            "The Orgy Chamber",
            "The Oubliette",
            "The Secret Hiding Place In The Hearth",
            "Secret Passages",
            "The Sickbed.",
            "The Torture Chamber",
            "The Trophy Room",
            "The Walled-Up Room",
            "The Wine Cellar"
        ]
    }, {
        "id": "gothic_objects",
        "title": "Gothic Objects",
        "roll": [
            "An Anatomical Venus",
            "An Automation",
            "A Blood-Stained Dagger",
            "A Book Of Anatomy",
            "A Cameo",
            "A Cerement, or Burial Shroud",
            "A Cloak",
            "A Coffin",
            "A Corpse Eaten By Animals",
            "A Deck Of Fortune-Telling Cards",
            "A Dissected Corpse",
            "A Dummy",
            "An Elaborate Bed",
            "An Exotic Weapon",
            "A Festival Mask",
            "Gloves",
            "A Grimoire",
            "An Iron Maiden",
            "Jars Filled With Strange Objects",
            "A Lady's Fan",
            "A Legendary Gem",
            "A Locket",
            "A Marionette",
            "A Memoir Filled With Disturbing Revelations",
            "A Mounted Animal Head",
            "A Mummified Hand",
            "A Murdered Corpse",
            "A Pipe Organ",
            "A Portrait",
            "A Ring With a Hidden Compartment",
            "A Robe",
            "A Skeleton",
            "A Skull",
            "A Spyglass",
            "A Suit Of Armor",
            "A Sword",
            "A Vial of Poison",
            "A Wax Sculpture",
            "A Wedding Gown",
            "A Wheel Of Fortune",
            "A Whip",
            "An Unusual Mirror",
            "Used Surgical Instruments"
        ]
    }, {
        "id": "gothic_characters",
        "title": "Gothic Characters",
        "roll": [
            "The Bandit With a Code of Honor",
            "The Beautiful Gypsy Woman",
            "The Black Widow",
            "The Boastful Man Who Challenges the Devil",
            "The Brutal Ruffian",
            "The Circus Freak",
            "The Criminal Anatomist",
            "The Cruel Relative",
            "The Deformed Henchman",
            "The Deluded Heretic",
            "The Depraved Religious Figure",
            "The Deranged Demoniac",
            "The Desperate Debtor",
            "The Desperate Drug Fiend",
            "The Diseased or Deformed Beggar",
            "The Disgusting Cannibal",
            "The Duplicitous Conspirator",
            "The Evil Nobleman",
            "The Exotic Slave",
            "The Feisty Woman Disguised As a Man",
            "The Femme Fatale",
            "The Frightened Innkeeper",
            "The Gentle Giant",
            "The Gentleman With A Troubled Past",
            "The Glib Philosopher",
            "The Greedy Banker",
            "The Gypsy Fortune Teller",
            "The Haughty Patron of the Arts",
            "The Ignored Prophet",
            "The Immoral Foreigner",
            "The Imprisoned Wife",
            "The Innocent Maiden",
            "The Insidious Succubus/Incubus",
            "The Insightful Clown",
            "The Knowing Madman",
            "The Lawyer With a Secret Agenda",
            "The Lonely Vampyre",
            "The Long-Lost Heir With a Murky Past",
            "The Long-Suffering But Dutiful Servant",
            "The Love-Struck Devil",
            "The Mad Scientist",
            "The Murderous Husband",
            "The Mysterious Stranger At the Door",
            "The Noble Savage",
            "The Obsessive Demon Hunter",
            "The Old Tinkerer With a Strange Artifact",
            "The Opportunistic Body Snatcher",
            "The Orphaned Governess or Nanny",
            "The Pathetic Child Beggar",
            "The Repentant Sinner",
            "The Ruthless Ship-Wrecker",
            "The Scheming Stepmother",
            "The Self-Made Man Whose Past Is a Lie",
            "The Senile Dowager",
            "The Sinister Dwarf",
            "The Sophisticated Courtesan",
            "The Stalwart Huntsman",
            "The Starving Peasant",
            "The Stubborn Skeptic",
            "The Stuffy Academic",
            "The Suicidal Lover",
            "The Swashbuckling Pirate",
            "The Tormented Artist",
            "The Tribesman With Savage Customs",
            "The Tricky, Pact-Making Devil",
            "The Twisted Necromancer",
            "The Vain Seductress",
            "The Virtuous, But Disinherited Nobleman",
            "The Vulgar Drunk",
            "The Werewolf Horrified By Himself",
            "The Wicked Libertine"
        ]
    }
]
